# Generated by Django 4.0.4 on 2023-07-25 20:53

from django.db import migrations
from utils.custom_helper import CustomPasscode

def create_mobile_assignment(apps, schema_editor):
    MobileAssignment = apps.get_model('v1_mobile', 'MobileAssignment')
    SystemUser = apps.get_model('v1_users', 'SystemUser')
    Access = apps.get_model('v1_profile', 'Access')
    from utils.custom_helper import generate_random_string, CustomJWT
    import datetime
    for user in SystemUser.objects.all():
        access = Access.objects.filter(user=user).first()
        if not access:
            continue
        token = CustomJWT().encode({
            "id": user.id,
            "email": user.email,
            "created_at": format(datetime.datetime.now(), "%Y-%m-%d"),
            "administration_id": access.administration.id,
            "exp": datetime.datetime.now() + datetime.timedelta(days=365253),
        })
        passcode = generate_random_string(8)
        MobileAssignment.objects.create(
            user=user,
            token=token,
            passcode=CustomPasscode().encode(passcode)
        )

def reverse_create_mobile_assignment(apps, schema_editor):
    MobileAssignment = apps.get_model('v1_mobile', 'MobileAssignment')
    MobileAssignment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('v1_mobile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mobile_assignment, reverse_create_mobile_assignment),
    ]
