---
version: "3.9"
services:
  backend:
    image: eu.gcr.io/akvo-lumen/rtmis/backend:latest
    working_dir: /app
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=rtmis
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DJANGO_SECRET=ci-secret
