---
version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
  backend:
    image: python:3.8.5
    working_dir: /app
    command: ["./start.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=rtmis
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
    depends_on:
      - db
    network_mode: service:mainnetwork
  frontend:
    image: node:17.3.0-alpine3.15
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      - EXAMPLE_SECRET="this is an example secret"
    depends_on:
      - backend
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  pg-data:
