---
version: "3.9"
services:
  backend:
    image: eu.gcr.io/akvo-lumen/national-wash-mis/backend:latest
    working_dir: /app/backend
    volumes:
      - ./:/app:delegated
      - ./storage:/app/storage:delegated
    environment:
      - TWILIO_ACCOUNT_SID=abc
      - TWILIO_AUTH_TOKEN=xyz
      - TWILIO_PHONE_NUMBER=12345678
      - GOOGLE_MAPS_API_KEY=secretkey
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DJANGO_SECRET=ci-secret
      - APK_UPLOAD_SECRET=ci-secret
      # env vars for coveralls
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN:-}
      - SEMAPHORE=${SEMAPHORE:-}
      - SEMAPHORE_JOB_ID=${SEMAPHORE_JOB_ID:-}
      - SEMAPHORE_WORKFLOW_ID=${SEMAPHORE_WORKFLOW_ID:-}
      - SEMAPHORE_GIT_PR_NUMBER=${SEMAPHORE_GIT_PR_NUMBER:-}
      - DEBUG=True
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - MAILJET_SECRET=$MAILJET_SECRET
      - WEBDOMAIN=notset
      - NWMIS_INSTANCE=burkina-faso
      - STORAGE_PATH="./storage"
    depends_on:
      - db
    command: tail -f /dev/null
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
