# Generated by Django 4.0.4 on 2023-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0020_alter_jmp_materialized_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
    ]
