# Generated by Django 4.0.4 on 2023-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0020_alter_jmp_materialized_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='translation',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='translation',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='translation',
            field=models.JSONField(default=None),
        ),
    ]
