---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${INSTANCE_NAME}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      run: ${INSTANCE_NAME}
  template:
    metadata:
      labels:
        run: ${INSTANCE_NAME}
        ${INSTANCE_NAME}-version: "${CI_COMMIT}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: frontend
          image: eu.gcr.io/akvo-lumen/national-wash-mis/frontend:${CI_COMMIT}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
        - name: backend
          image: eu.gcr.io/akvo-lumen/national-wash-mis/backend:${CI_COMMIT}
          ports:
            - containerPort: 8000
          env:
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-schema
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-host
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: django-secret
            - name: MAILJET_APIKEY
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: mailjet-apikey
            - name: MAILJET_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: mailjet-secret
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: email-from
            - name: WEBDOMAIN
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: webdomain
            - name: NWMIS_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: instance
            - name: PROD
              value: "TRUE"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
          readinessProbe:
            httpGet:
              path: /api/v1/health/check
              port: 8000
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /api/v1/health/check
              port: 8000
            initialDelaySeconds: 30
          volumeMounts:
            - name: ${INSTANCE_NAME}-secrets
              mountPath: /secrets/credentials.json
              subPath: nwmis-service-account.json
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
        - name: worker
          image: eu.gcr.io/akvo-lumen/national-wash-mis/worker:${CI_COMMIT}
          env:
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-schema
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: db-host
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: django-secret
            - name: MAILJET_APIKEY
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: mailjet-apikey
            - name: MAILJET_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: mailjet-secret
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: email-from
            - name: WEBDOMAIN
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: webdomain
            - name: NWMIS_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE_NAME}
                  key: instance
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
          volumeMounts:
            - name: ${INSTANCE_NAME}-secrets
              mountPath: /secrets/credentials.json
              subPath: nwmis-service-account.json
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
      volumes:
        - name: ${INSTANCE_NAME}-secrets
          secret:
            secretName: ${INSTANCE_NAME}
