kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${INSTANCE_NAME}
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
