# Generated by Django 4.0.4 on 2023-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_jobs', '0002_jobs_task_id_alter_jobs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='completed',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='total',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'on_progress'), (3, 'failed'), (4, 'done'), (5, 'chunk')], default=1),
        ),
    ]
